### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ytaylordev** [Adalab/modulo-3-evaluacion-intermedia-lauramargo#1]
Buen trabajo @lauramargo  !

### Algunas pistas para acabarlo:

- [ ] Elimina la carpeta `node_modules` de git y GitHub.
- [x] Obtén los datos del API con un fetch()
- [x] Usa un `<form>` para cada grupo de `<input>`, no es necesario que crees un `form` por cada input: https://github.com/Adalab/modulo-3-evaluacion-intermedia-lauramargo/blob/901c9772c550e6f07f8670c2ab30c8d6896492bf/src/components/App.js#L57 
- [x] Pon un `<label>` para indicar para qué es cada `<input>` y recuerda asociarlos con el atributo `htmlFor`: https://github.com/Adalab/modulo-3-evaluacion-intermedia-lauramargo/blob/901c9772c550e6f07f8670c2ab30c8d6896492bf/src/components/App.js#L72 
- [x] Verifica el filter de personajes y de frases.
- [x] Añade un título `h1` a la página (Frases de Friends)
- [x] Incluye el elemento del título dentro de la etiqueta `<header>`
- [x] Comprueba que los `inputs` tengan algún valor cuando vas a añadir una nueva frase. 
- [x] Revisa los metadatos en `index.html` (`lang`, `title`...)

> Recuerda: a medida que vayas realizando estas mejoras debes subirlas a la rama principal de este repo y marcarlas como realizadas en este issue. Si no, tu profe no sabrás que has realizado estas mejoras.

Si tienes cualquier duda, ¡avisa!

Al turrón!!!

**Comment by lauramargo** [comment]
he intentado quitar la carpeta de node modules, pero algo estoy haciendo mal, he creado la carpeta gitignore, he metido  esto (/node_modules) dentro de la carpeta, he borrado en local la carpeta node modules y luego en la terminal puesto esto (git rm --cached -r ./node_modules), pero me da fallo y tengo que retornat y borrar el commit.

**Comment by ytaylordev** [comment]
Los pasos par eliminar una carpeta de node modules que ya está en Git son los siguientes: 

- En el archivo .gitignore del proyecto añadir /node_modules.
- Eliminar la carpeta de  node modules de tu proyecto
- Ejecuta el comando `git add -A`, `git commit -m ` y `git push`
- Instala otra vez los paquetes de node_modules con npm install


Prueba de esta manera, a ver si te sale, sino solicita una tutoría o buscamos un huequito :)
